import matplotlib
import matplotlib.pyplot as plt
import numpy as np

train_loss = np.loadtxt("base_loss.csv", delimiter=',', skiprows=1, usecols=1)
base_loss = np.loadtxt("base_loss.csv", delimiter=',', skiprows=1, usecols=2)
dropout_loss = np.loadtxt("dropout_loss.csv", delimiter=',', skiprows=1, usecols=2)
sgld_loss = np.loadtxt("sgld_loss.csv", delimiter=',', skiprows=1, usecols=2)

fig = plt.figure()
plt.plot(train_loss)
plt.plot(base_loss)
plt.plot(dropout_loss)
plt.plot(sgld_loss)
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['training_loss', 'base_loss', 'dropout_loss', 'sgld_loss']) 
fig.savefig('combined.png')   
plt.show()
plt.close(fig)

fig = plt.figure()
plt.plot(base_loss)
plt.plot(dropout_loss)
plt.plot(sgld_loss)
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['base model', 'base model with dropout', 'SG MCMC']) 
fig.savefig('combined_no_train.png')   
plt.show()
plt.close(fig)

fig = plt.figure()
plt.plot(base_loss)
plt.title('base model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['base_loss']) 
fig.savefig('base_loss.png')   
plt.show()
plt.close(fig)

fig = plt.figure()
plt.plot(dropout_loss)
plt.title('dropout model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['dropout_loss']) 
fig.savefig('dropout_loss.png')   
plt.show()
plt.close(fig)

fig = plt.figure()
plt.plot(sgld_loss)
plt.title('sgld model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['sgld_loss']) 
fig.savefig('sgld_loss.png')   
plt.show()
plt.close(fig)